### ISSUE TITLE
Testers needed.

### ISSUE THREAD

**Issue by TheRocker7421** [TheRocker7421/super-octocat#1]
We need a Mac tester and a Linux tester. Anyone out there to help us?

**Comment by TheRocker7421** [comment]
Anyone?

**Comment by AeriaVelocity** [comment]
What is this exactly?

**Comment by TheRocker7421** [comment]
This is an adventure game written in Batchfile and Bash. You try to collect the HTML code and defeat the boss Doctor Corruptor.

**Comment by TheRocker7421** [comment]
P.S. Sorry for the late response.

**Comment by AeriaVelocity** [comment]
And you need someone to test the bash version on a *nix system, is that right?

**Comment by TheRocker7421** [comment]
Yes.

**Comment by TheRocker7421** [comment]
Would WSL work for a *nix system?

**Comment by AeriaVelocity** [comment]
Tested `super-octocat-linux.sh` on Alpine. Seems to work fine.

By the way, there should be no reason to have two shell scripts, each for Linux and macOS.
Both systems can read the same bash scripts the same; you should consider removing one and generalising the kept file.
It'd be easier to make changes as well, since you'd only have to edit two files instead of three.

**Comment by AeriaVelocity** [comment]
![image](https://user-images.githubusercontent.com/16748384/132592103-b12e9629-98e8-472e-b00c-5e288938e324.jpeg)

**Comment by TheRocker7421** [comment]
Thanks for the tip! Would you be willing to test the commits made?

**Comment by AeriaVelocity** [comment]
> Would WSL work for a *nix system?

WSL is a real Linux system, so yes.

**Comment by TheRocker7421** [comment]
Okay!

**Comment by AeriaVelocity** [comment]
> Thanks for the tip! Would you be willing to test the commits made?

Sure, I don't mind.

**Comment by TheRocker7421** [comment]
Okay! Thanks! Closing the issue.
